### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by jacobseiler**
This PR just adds a link to `index.rst` to the README.

Please do a squash merge because apparently my commit history on my fork is super messe up...

### CODE REVIEW

**Comment by manodeep** [comment]
That looks like a mess! Squash-merge it is

**Comment by manodeep** [comment]
Wait, does this include the binary file additions? May be close this PR and then open a new one from a clean branch?

**Comment by jacobseiler** [comment]
Which binary files are you referring to?  

The PR says only 1 file is changed (the README) so I thought it was all good...

**Comment by jacobseiler** [comment]
[Closed due to update being made to master directly.](bb110d576606c1a1006a51e33beb33ab0b6ff54f)

**Pull request closed without merging**
