### PR TITLE
Added introduction to Qt5 tutorial.

### PR DESCRIPTION
**Pull request by 1313e**

### CODE REVIEW

**Comment by manodeep** [comment]
@1313e Thanks for adding in the files from your session. 

Looks like the `pptx` file is not needed. Do you mind removing that file from this PR?

**Comment by 1313e** [comment]
I just added it as the source file for the PDF version.
After all, exporting PowerPoint to PDF reduces its quality.

**Comment by manodeep** [comment]
Then will you please add a `tutorials/Intro_to_QT5/README.rst` file and add in both the links to the pdf and the pptx in that README?

The links in the `index.rst` and the `README.rst` in the root of the repo should be altered to point to this new README file

**Comment by 1313e** [comment]
Sure

**Comment by 1313e** [comment]
@manodeep There you go.

**Comment by manodeep** [comment]
Thanks @1313e

**Pull request merged**
