### PR TITLE
Added mpi4py sample data

### PR DESCRIPTION
**Pull request by abatten**
* Added 4 text files with 4 columns of data.
* Each column has a different distribution.
* The task is to parallelise making histograms from the data.

### CODE REVIEW

**Comment by manodeep** [comment]
@abatten Could you rename the columns to have physical meanings? (Rather than 'Data1/Data2/' etc)

**Comment by abatten** [comment]
Yes, I can do that. Although the data itself doesn't actually have any physical meaning. I just picked some random values for some distributions.

**Comment by manodeep** [comment]
@abatten Ahh okay! Then could you rename to "col1, col2, " etc...

**Comment by abatten** [comment]
I have "made up" some possible realistic names, i.e the radius of a galaxy, the velocity of the galaxy, the number of satellites and some other "factor".

We also added some MUSE spectra data with 4 LOS through the cube. There is both flux and varience data.

**Pull request merged**
