### PR TITLE
Added tutorial on Python decorators and factories

### PR DESCRIPTION
**Pull request by 1313e**

### CODE REVIEW

**Comment by abatten** [comment]
You know this would have been the perfect use case for a jupyter notebook. :P But I'll let this slide. This looks fine to merge. I'm thinking squash merge right @manodeep?

**Comment by jacobseiler** [comment]
Is it possible to add a "Wrapping Up" Section to the end of this?  Basically summarising the main/key points. You could also add a few links for further reading (e.g., the [pycon2019 presentation on decorators](https://www.youtube.com/watch?v=MjHpMCIvwsY)).

**Comment by 1313e** [comment]
@jacobseiler Sure.
@abatten I know, I was thinking about making one.
However, as much as I dislike them, I have very rarely used them and therefore don't really know well enough how to write them properly.

**Comment by manodeep** [comment]
Looks good to me. @1313e - please let me know if you are planning to implement @jacobseiler suggestion - I do think that a "Take-away" section will be beneficial for people skimming the material. 

Once you are finished, I am happy to merge the PR.

**Comment by 1313e** [comment]
@manodeep I already did what Jacob asked for.

**Comment by 1313e** [comment]
Crap, I just found that I made a mistake somewhere, where I did not use a whiteline.
Guess I will have to make a new PR just for that one line.

**Comment by 1313e** [comment]
Ugh, I just found out that I forgot a whiteline somewhere.
@manodeep Can you add a whiteline between lines 239 and 240 in the README.rst of the decorators review?

**Pull request merged**
